theme: jekyll-theme-cayman
title: Human Mobility Index
subtitle: Ömer Özak (c)
description: "Measuring mobility around the globe across time <br> Ömer Özak (c) 2010"
show_downloads: true
google_analytics: UA-48650617-4
github:
  is_project_page: true
# About/contact
author:
  name:       Ömer Özak
  url:        http://omerozak.com
